export const GET_COUPONS_FETCH = 'GET_COUPONS_FETCH';
export const GET_COUPONS_SUCCESS = 'GET_COUPONS_SUCCESS';
export const GET_COUPONS_ERROR = 'GET_COUPONS_ERROR';

export const SELECT_COUPON = 'SELECT_COUPON';
export const CLOSE_COUPON = 'CLOSE_COUPON';
