export const GET_CITY_LIST_FETCH = 'GET_CITY_LIST_FETCH';
export const GET_CITY_LIST_SUCCESS = 'GET_CITY_LIST_SUCCESS';
export const GET_CITY_LIST_ERROR = 'GET_CITY_LIST_ERROR';
export const CLEAR_CITY_LIST = 'CLEAR_CITY_LIST';
