export const SEND_CONFIRM_CODE_FETCH = 'SEND_CONFIRM_CODE_FETCH';
export const SEND_CONFIRM_CODE_SUCCESS = 'SEND_CONFIRM_CODE_SUCCESS';
export const SEND_CONFIRM_CODE_ERROR = 'SEND_CONFIRM_CODE_ERROR';

export const CHECK_CONFIRM_CODE_FETCH = 'CHECK_CONFIRM_CODE_FETCH';
export const CHECK_CONFIRM_CODE_SUCCESS = 'CHECK_CONFIRM_CODE_SUCCESS';
export const CHECK_CONFIRM_CODE_REPEAT = 'CHECK_CONFIRM_CODE_REPEAT';
export const CHECK_CONFIRM_CODE_ERROR = 'CHECK_CONFIRM_CODE_ERROR';

export const RESET_CONFIRM_CODE = 'RESET_CONFIRM_CODE';
export const RESET_PROGRESS = 'RESET_PROGRESS';
