export const USER_ACTION_FETCH = 'USER_ACTION_FETCH';
export const USER_GET_LOCAL_DATA = 'USER_GET_LOCAL_DATA';

export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR';

export const USER_REGISTER_ERROR = 'USER_REGISTER_ERROR';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';

export const USER_EDIT_ERROR = 'USER_EDIT_ERROR';
export const USER_EDIT_SUCCESS = 'USER_EDIT_SUCCESS';

export const USER_RESTORE_PASSWORD_SUCCESS = 'USER_RESTORE_PASSWORD_SUCCESS';
export const USER_RESTORE_PASSWORD_ERROR = 'USER_RESTORE_PASSWORD_ERROR';
export const USER_RESTORE_PASSWORD_RESET = 'USER_RESTORE_PASSWORD_RESET';

export const USER_CHANGE_PASSWORD_SUCCESS = 'USER_CHANGE_PASSWORD_SUCCESS';
export const USER_CHANGE_PASSWORD_ERROR = 'USER_CHANGE_PASSWORD_ERROR';

export const USER_LOGOUT = 'USER_LOGOUT';
